/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

import pack_logica.Usuario;
import pack_estructuras.ListaEnlazada;
/**
 *
 * @author DELL
 */
public class frmAdminSelector extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAdminSelector.class.getName());
    
    // Variable global para guardar la lista
    private ListaEnlazada<Usuario> listaUsuarios;

    // Modificamos el constructor para recibir la lista de usuarios
    public frmAdminSelector(ListaEnlazada<Usuario> usuarios) {
        this.listaUsuarios = usuarios;
        initComponents();
        
        // Agregar los roles manualmente (si no lo hiciste en las propiedades visuales)
        cbRoles.removeAllItems();
        cbRoles.addItem("doctor");
        cbRoles.addItem("paciente");
        cbRoles.addItem("farmaceutico");
        
        cargarUsuarios(); // Llenamos la lista de usuarios inicial
    }
    
    // Método para filtrar usuarios según el rol seleccionado
    private void cargarUsuarios() {
        cbUsuarios.removeAllItems();
        if (cbRoles.getSelectedItem() == null) return;
        
        String rolElegido = cbRoles.getSelectedItem().toString();
        
        for (int i = 0; i < listaUsuarios.getTamaño(); i++) {
            Usuario u = listaUsuarios.obtener(i);
            String correo = u.getUsername();
            if (correo.contains("_" + rolElegido + "@")) {
                cbUsuarios.addItem(correo);
            }
        }
    }
    /**
     * Creates new form frmAdminSelector
     */
    public frmAdminSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bIniciarsesion = new javax.swing.JButton();
        pEncabezadoLogin = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        cbRoles = new javax.swing.JComboBox<>();
        cbUsuarios = new javax.swing.JComboBox<>();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        bIniciarsesion.setBackground(new java.awt.Color(153, 153, 255));
        bIniciarsesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bIniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarsesion.setText("Iniciar Sesión");
        bIniciarsesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bIniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bIniciarsesionMouseClicked(evt);
            }
        });
        bIniciarsesion.addActionListener(this::bIniciarsesionActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pEncabezadoLogin.setBackground(new java.awt.Color(70, 130, 180));

        lLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lLogin.setForeground(new java.awt.Color(255, 255, 255));
        lLogin.setText("Admin Selector");

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout pEncabezadoLoginLayout = new javax.swing.GroupLayout(pEncabezadoLogin);
        pEncabezadoLogin.setLayout(pEncabezadoLoginLayout);
        pEncabezadoLoginLayout.setHorizontalGroup(
            pEncabezadoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncabezadoLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(lLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEncabezadoLoginLayout.setVerticalGroup(
            pEncabezadoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEncabezadoLoginLayout.createSequentialGroup()
                .addGroup(pEncabezadoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEncabezadoLoginLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lLogin))
                    .addGroup(pEncabezadoLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "doctor", "paciente", "farmaceutico" }));
        cbRoles.addActionListener(this::cbRolesActionPerformed);

        cbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIniciar.setBackground(new java.awt.Color(153, 153, 255));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Entrar");
        btnIniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        jLabel1.setText("Seleccione el rol sobre el que quiere gestionar los datos");

        jLabel2.setText("Seleccione el usuario respectivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(cbUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addComponent(pEncabezadoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pEncabezadoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnIniciar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarsesionMouseClicked
        
    }//GEN-LAST:event_bIniciarsesionMouseClicked

    private void bIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bIniciarsesionActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmlogin login = new frmlogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String correoDestino = (String) cbUsuarios.getSelectedItem();
    
        if (correoDestino == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay usuarios disponibles.");
            return;
        }

        String rolDestino = cbRoles.getSelectedItem().toString();

        // Extracción del nombre a partir del correo
        String nombreDestino = correoDestino.substring(0, correoDestino.indexOf("_")).replace(".", " ");
        nombreDestino = nombreDestino.substring(0, 1).toUpperCase() + nombreDestino.substring(1);

        // Redirección a la ventana respectiva dependiendo del rol
        if (rolDestino.equals("doctor")) {
            String idMedicoDestino = correoDestino.split("@")[0].split("_")[0];
            new frmMedico("Dr. " + nombreDestino + " (Admin)", idMedicoDestino).setVisible(true);
        } else if (rolDestino.equals("paciente")) {
            new frmPaciente(nombreDestino + " (Admin)", correoDestino).setVisible(true);
        } else if (rolDestino.equals("farmaceutico")) {
            new frmFarmaceutico(nombreDestino + " (Admin)").setVisible(true);
        }

        this.dispose(); // Cierre de la ventana selectora
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void cbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolesActionPerformed
        // TODO add your handling code here:
        cargarUsuarios();
    }//GEN-LAST:event_cbRolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAdminSelector().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciarsesion;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbRoles;
    private javax.swing.JComboBox<String> cbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lLogin;
    private javax.swing.JPanel pEncabezadoLogin;
    // End of variables declaration//GEN-END:variables
}
