/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
import pack_estructuras.*;
import pack_logica.*;

/**
 *
 * @author HP
 */
public class frmlogin extends javax.swing.JFrame {
    
    private ListaEnlazada<Usuario> listaUsuarios = new ListaEnlazada<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmlogin.class.getName());
    private static final String HIDEN_KEY = "2406200611012026";

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        cargarDatosCSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondoLogin = new javax.swing.JPanel();
        lUsuario = new javax.swing.JLabel();
        lcontrasena = new javax.swing.JLabel();
        bIniciarsesion = new javax.swing.JButton();
        bCrearCuenta = new javax.swing.JButton();
        tUsuario = new javax.swing.JTextField();
        pContrasena = new javax.swing.JPasswordField();
        pEncabezadoLogin = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login-Vital Core");
        setResizable(false);

        pFondoLogin.setBackground(java.awt.SystemColor.control);

        lUsuario.setText("Usuario");

        lcontrasena.setText("Contraseña");

        bIniciarsesion.setBackground(new java.awt.Color(153, 153, 255));
        bIniciarsesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bIniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarsesion.setText("Iniciar Sesión");
        bIniciarsesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bIniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bIniciarsesionMouseClicked(evt);
            }
        });
        bIniciarsesion.addActionListener(this::bIniciarsesionActionPerformed);

        bCrearCuenta.setBackground(new java.awt.Color(102, 255, 204));
        bCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        bCrearCuenta.setText("Crear Cuenta");
        bCrearCuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCrearCuentaMouseClicked(evt);
            }
        });
        bCrearCuenta.addActionListener(this::bCrearCuentaActionPerformed);

        tUsuario.addActionListener(this::tUsuarioActionPerformed);

        pContrasena.addActionListener(this::pContrasenaActionPerformed);

        pEncabezadoLogin.setBackground(new java.awt.Color(70, 130, 180));

        lLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lLogin.setForeground(new java.awt.Color(255, 255, 255));
        lLogin.setText("Login");

        javax.swing.GroupLayout pEncabezadoLoginLayout = new javax.swing.GroupLayout(pEncabezadoLogin);
        pEncabezadoLogin.setLayout(pEncabezadoLoginLayout);
        pEncabezadoLoginLayout.setHorizontalGroup(
            pEncabezadoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEncabezadoLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lLogin)
                .addGap(136, 136, 136))
        );
        pEncabezadoLoginLayout.setVerticalGroup(
            pEncabezadoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEncabezadoLoginLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lLogin)
                .addGap(17, 17, 17))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_gui/images/VITAL-CORE (1)4peq.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(298, 348));

        javax.swing.GroupLayout pFondoLoginLayout = new javax.swing.GroupLayout(pFondoLogin);
        pFondoLogin.setLayout(pFondoLoginLayout);
        pFondoLoginLayout.setHorizontalGroup(
            pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEncabezadoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFondoLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pFondoLoginLayout.createSequentialGroup()
                        .addComponent(lcontrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFondoLoginLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCrearCuenta)
                    .addComponent(bIniciarsesion))
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        pFondoLoginLayout.setVerticalGroup(
            pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLoginLayout.createSequentialGroup()
                .addComponent(pEncabezadoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuario)
                    .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcontrasena))
                .addGap(18, 18, 18)
                .addComponent(bIniciarsesion)
                .addGap(18, 18, 18)
                .addComponent(bCrearCuenta)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bIniciarsesionActionPerformed

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void pContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pContrasenaActionPerformed

    private void bIniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarsesionMouseClicked
        String user = tUsuario.getText().trim().toLowerCase();
        String pass = encriptar(new String(pContrasena.getPassword()));
        

    boolean autenticado = false;
    Usuario usuarioEncontrado = null;

    // Recorrido lineal sobre la estructura personalizada
    for (int i = 0; i < listaUsuarios.getTamaño(); i++) {
        Usuario u = listaUsuarios.obtener(i);
        if (u.getUsername().equals(user) && u.getPassword().equals(pass)) {
            autenticado = true;
            usuarioEncontrado = u;
            break; // Detiene la búsqueda al encontrar coincidencia
        }
    }

    if (autenticado && usuarioEncontrado != null) {
        
        String typeUser = "";
        String nombreUsuario = "";
        
        if (user.contains("_")) {
            int posicionInicio = user.lastIndexOf("_") + 1;
            int posicionFin = user.indexOf("@");
            typeUser = user.substring(posicionInicio, posicionFin);
            
            // Extraer nombre del usuario
            nombreUsuario = user.substring(0, user.indexOf("_"));
            nombreUsuario = nombreUsuario.replace(".", " ");
            nombreUsuario = nombreUsuario.substring(0, 1).toUpperCase() + nombreUsuario.substring(1);
        }

        switch (typeUser) {
            case "admin":
                JOptionPane.showMessageDialog(this, "Bienvenido, Administrador.");
                // Nueva instancia del Admin Selector y uso del parametro de la lista de usuarios listaEnlazada de usuarios
                frmAdminSelector selector = new frmAdminSelector(listaUsuarios);
                selector.setVisible(true);
                selector.setLocationRelativeTo(null);
                this.dispose(); // Cierre del login
                break;
            case "doctor":
                JOptionPane.showMessageDialog(this, "Bienvenido, Doctor. Sus consultas del día están listas.");
                String idMedico = "";
                try {
                    String[] partesCorreo = user.split("@")[0].split("_");
                    if (partesCorreo.length > 0) {
                        idMedico = partesCorreo[0];
                    }
                } catch (Exception e) {
                    idMedico = "default"; 
                }
                frmMedico ventanaMedico = new frmMedico("Dr. " + nombreUsuario, idMedico);
                ventanaMedico.setVisible(true);
                ventanaMedico.setLocationRelativeTo(null);
                this.dispose();
                break;
            case "paciente":
                JOptionPane.showMessageDialog(this, "Hola. Aquí puedes revisar tus citas médicas y recetas.");
                String idPaciente = user;
                frmPaciente paciente = new frmPaciente(nombreUsuario, user);
                paciente.setVisible(true);
                this.setVisible(false);
                break;
            case "farmaceutico":
                JOptionPane.showMessageDialog(this, "Acceso concedido. Inventario de farmacia disponible.");
                frmFarmaceutico farm = new frmFarmaceutico(nombreUsuario);
                farm.setVisible(true);
                this.setVisible(false);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Bienvenido al sistema Vital-Core.");
                break;
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de Acceso", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bIniciarsesionMouseClicked

    private void bCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCrearCuentaMouseClicked

    }//GEN-LAST:event_bCrearCuentaMouseClicked
    
    private void bCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearCuentaActionPerformed
        frmregistro ventanaRegistro = new frmregistro(); 
        ventanaRegistro.setVisible(true); 
        ventanaRegistro.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_bCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public String encriptar(String datos) {
        try {
            SecretKeySpec secretKey = new SecretKeySpec(HIDEN_KEY.getBytes(), "AES");
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            byte[] datosEncriptados = cipher.doFinal(datos.getBytes());
            return Base64.getEncoder().encodeToString(datosEncriptados);
        } catch (Exception e) {
            return null;
        }
    }
    
    private void cargarDatosCSV() {
        File archivo = new File("usuarios.csv");
        if (!archivo.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            br.readLine(); // Salto de la cabecera (usuario,contraseña)
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length == 2) {
                    Usuario uLeido = new Usuario(datos[0], datos[1]);
                    listaUsuarios.agregar(uLeido);
                }
            }
        } catch (IOException e) {
            System.err.println("Error al cargar: " + e.getMessage());
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmlogin().setVisible(true);
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearCuenta;
    private javax.swing.JButton bIniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JLabel lcontrasena;
    private javax.swing.JPasswordField pContrasena;
    private javax.swing.JPanel pEncabezadoLogin;
    private javax.swing.JPanel pFondoLogin;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
