/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import java.awt.Component;
import pack_estructuras.*;

/**
 *
 * @author USUARIO
 */
public class frmMedico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMedico.class.getName());
    
    private String nombreMedico;
    private String idMedico;

    public frmMedico() {
        this("Dr. Médico", "M001");
    }
    
    public frmMedico(String nombreMedico, String idMedico) {
        this.nombreMedico = nombreMedico;
        this.idMedico = idMedico;
        initComponents();
        lBienvenida.setText("Bienvenido, " + nombreMedico);
        cargarDatosCitas();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEncabezadoM = new javax.swing.JPanel();
        lBienvenida = new javax.swing.JLabel();
        lSistemaGestionM = new javax.swing.JLabel();
        tabpCitasMedicas = new javax.swing.JTabbedPane();
        pCitasAgendadas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasAgendadas = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        pCitasAtendidas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitasAtendidas = new javax.swing.JTable();
        btnVerDetalles = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Médico");
        setPreferredSize(new java.awt.Dimension(950, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pEncabezadoM.setBackground(new java.awt.Color(70, 130, 180));
        pEncabezadoM.setPreferredSize(new java.awt.Dimension(950, 90));
        pEncabezadoM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lBienvenida.setText("Bienvenido Dr. Médico");
        lBienvenida.setPreferredSize(new java.awt.Dimension(250, 30));
        pEncabezadoM.add(lBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        lSistemaGestionM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lSistemaGestionM.setForeground(new java.awt.Color(255, 255, 255));
        lSistemaGestionM.setText("Sistema de Gestión Médica");
        lSistemaGestionM.setPreferredSize(new java.awt.Dimension(400, 40));
        pEncabezadoM.add(lSistemaGestionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        getContentPane().add(pEncabezadoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabpCitasMedicas.setPreferredSize(new java.awt.Dimension(930, 470));

        pCitasAgendadas.setBackground(new java.awt.Color(255, 255, 255));
        pCitasAgendadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 360));

        tablaCitasAgendadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAgendadas.setRowHeight(25);
        jScrollPane1.setViewportView(tablaCitasAgendadas);

        pCitasAgendadas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnRefrescar.setBackground(new java.awt.Color(100, 149, 237));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setFocusPainted(false);
        btnRefrescar.setPreferredSize(new java.awt.Dimension(110, 35));
        btnRefrescar.addActionListener(this::btnRefrescarActionPerformed);
        pCitasAgendadas.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        btnAtender.setBackground(new java.awt.Color(60, 179, 113));
        btnAtender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("Atender Cita");
        btnAtender.setFocusPainted(false);
        btnAtender.setPreferredSize(new java.awt.Dimension(110, 35));
        btnAtender.addActionListener(this::btnAtenderActionPerformed);
        pCitasAgendadas.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 120, -1));

        tabpCitasMedicas.addTab("CItas Agendadas", pCitasAgendadas);

        pCitasAtendidas.setBackground(new java.awt.Color(255, 255, 255));
        pCitasAtendidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(900, 360));

        tablaCitasAtendidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasAtendidas.setRowHeight(25);
        jScrollPane2.setViewportView(tablaCitasAtendidas);

        pCitasAtendidas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnVerDetalles.setBackground(new java.awt.Color(100, 149, 237));
        btnVerDetalles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalles.setText("Ver Detalles");
        btnVerDetalles.setFocusPainted(false);
        btnVerDetalles.setPreferredSize(new java.awt.Dimension(100, 35));
        btnVerDetalles.addActionListener(this::btnVerDetallesActionPerformed);
        pCitasAtendidas.add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 130, -1));

        tabpCitasMedicas.addTab("Citas Atendidas", pCitasAtendidas);

        getContentPane().add(tabpCitasMedicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(220, 20, 60));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(130, 25));
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Merge sort: ordena las citas por fecha y hora
    public pack_logica.Cita[] ordenarCitasMergeSort(pack_logica.Cita[] arreglo) {
        if (arreglo.length <= 1) {
            return arreglo; // Caso base: un arreglo de 1 o 0 elementos ya está ordenado
        }

        int medio = arreglo.length / 2;
        // División del arreglo en dos mitades
        pack_logica.Cita[] izquierda = java.util.Arrays.copyOfRange(arreglo, 0, medio);
        pack_logica.Cita[] derecha = java.util.Arrays.copyOfRange(arreglo, medio, arreglo.length);

        // Llamadas recursivas
        izquierda = ordenarCitasMergeSort(izquierda);
        derecha = ordenarCitasMergeSort(derecha);

        // Union de ambas mitades
        return merge(izquierda, derecha);
    }

    // Une las dos mitades ya ordenadas en una sola
    private pack_logica.Cita[] merge(pack_logica.Cita[] izquierda, pack_logica.Cita[] derecha) {
        pack_logica.Cita[] resultado = new pack_logica.Cita[izquierda.length + derecha.length];
        int i = 0, j = 0, k = 0;

        while (i < izquierda.length && j < derecha.length) {
            // Criterio para evaluar fechas y horas
            if (criterioCronologico(izquierda[i], derecha[j])) {
                resultado[k++] = izquierda[i++];
            } else {
                resultado[k++] = derecha[j++];
            }
        }
        while (i < izquierda.length) { resultado[k++] = izquierda[i++]; }
        while (j < derecha.length) { resultado[k++] = derecha[j++]; }

        return resultado;
    }

    // Compara primero por fecha, si empatan compara por hora
    private boolean criterioCronologico(pack_logica.Cita c1, pack_logica.Cita c2) {
        // Comparación de las fechas
        int comparacionFecha = c1.getFecha().compareTo(c2.getFecha());

        if (comparacionFecha != 0) {
            return comparacionFecha < 0; // Retorna true si c1 es anterior a c2
        }

        //Si son exactamente el mismo día, el que tenga la hora más temprana va primero
        return c1.getHora().compareTo(c2.getHora()) < 0;
    }
    
    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        // TODO add your handling code here:
        atenderCita();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        cargarCitasAgendadas();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        // TODO add your handling code here:
        verDetalles();
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    
    private void cargarDatosCitas() {
        javax.swing.table.DefaultTableModel modeloAgendadas = 
            (javax.swing.table.DefaultTableModel) tablaCitasAgendadas.getModel();
        javax.swing.table.DefaultTableModel modeloAtendidas = 
            (javax.swing.table.DefaultTableModel) tablaCitasAtendidas.getModel();

        modeloAgendadas.setRowCount(0);
        modeloAtendidas.setRowCount(0);

        java.io.File archivo = new java.io.File("citas.csv");
        if (!archivo.exists()) return;

        // Se separan las citas del doctor segun su estado
        java.util.ArrayList<pack_logica.Cita> listaTemporalAgendadas = new java.util.ArrayList<>();
        java.util.ArrayList<pack_logica.Cita> listaTemporalAtendidas = new java.util.ArrayList<>();

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea = br.readLine(); // Saltar encabezado

            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) continue;
                String[] datos = linea.split(",");

                // Formato exacto de 9 columnas
                if (datos.length >= 9) {
                    String idCita = datos[0];
                    String nombrePaciente = datos[2]; 
                    String fecha = datos[3];
                    String hora = datos[4];
                    String nombreMedicoCSV = datos[5]; // Nombre guardado en el archivo
                    String idMedicoCSV = datos[6];     // ID o correo guardado en el archivo
                    String motivo = datos[7];
                    String estado = datos[8];


                    if (nombreMedicoCSV.equals(this.nombreMedico) || 
                        idMedicoCSV.equals(this.idMedico) || 
                        this.idMedico.equals("default")) {

                        pack_logica.Cita nuevaCita = new pack_logica.Cita(idCita, fecha, hora, nombrePaciente, motivo, estado);

                        if (estado.equals("Agendada")) {
                            listaTemporalAgendadas.add(nuevaCita);
                        } else if (estado.equals("Atendida") || estado.equals("No se presentó")) {
                            listaTemporalAtendidas.add(nuevaCita);
                        }
                    }
                }
            }
        } catch (java.io.IOException e) {
            System.err.println("Error al cargar citas: " + e.getMessage());
        }

        // Las agendadas se ordenan antes de mostrarlas
        pack_logica.Cita[] arregloDesordenado = listaTemporalAgendadas.toArray(new pack_logica.Cita[0]);
        pack_logica.Cita[] arregloOrdenado = ordenarCitasMergeSort(arregloDesordenado);

        for (pack_logica.Cita c : arregloOrdenado) {
            Object[] fila = {c.getIdCita(), c.getFecha(), c.getHora(), c.getMedico(), c.getMotivo(), c.getEstado()};
            modeloAgendadas.addRow(fila);
        }

        for (pack_logica.Cita c : listaTemporalAtendidas) {
            Object[] fila = {c.getIdCita(), c.getFecha(), c.getHora(), c.getMedico(), c.getMotivo(), c.getEstado()};
            modeloAtendidas.addRow(fila);
        }
    }
    
    //Metodo de actualización de las citas en el archivo CSV
    private void actualizarEstadoCitaEnCSV(String idCita, String nuevoEstado) {
        java.io.File archivo = new java.io.File("citas.csv");
        if (!archivo.exists()) {
            return;
        }
        ListaEnlazada<String> lineas = new ListaEnlazada<>();

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea = br.readLine(); 
            lineas.agregar(linea);

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos[0].equals(idCita)) {
                    if (datos.length >= 9) {
                        datos[8] = nuevoEstado;
                }
                    lineas.agregar(String.join(",", datos));
                } else {
                    lineas.agregar(linea);
                }
            }
        } catch (java.io.IOException e) {
            System.err.println("Error al leer citas: " + e.getMessage());
            return;
        }

        // Reescribir el archivo
        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
            for (int i = 0; i < lineas.getTamaño(); i++) {
                String linea = lineas.obtener(i);
                pw.println(linea);
            }
        } catch (java.io.IOException e) {
            System.err.println("Error al actualizar citas: " + e.getMessage());
        }
    }
    
    
    private void cargarCitasAgendadas() {
        cargarDatosCitas();
        javax.swing.JOptionPane.showMessageDialog(this, "Citas actualizadas");
    }
    
    private void atenderCita() {
        int fila = tablaCitasAgendadas.getSelectedRow();
        if (fila == -1) {
            //Se debe seleccionar una columna para atender
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cita para atender");
            return;
        }

        //Obtención de los datos de la cita
        String idCita = (String) tablaCitasAgendadas.getValueAt(fila, 0);
        String paciente = (String) tablaCitasAgendadas.getValueAt(fila, 3);

        // Se abre la ventana de atencion y se espera a que cierre
        frmAtenderCita ventana = new frmAtenderCita(idCita, paciente);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(this);

        // Esperar a que se cierre la ventana y actualizar la tabla
        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            //Metodo de manipulación entre ambas ventanas
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Solo se mueve la cita si realmente se atendio
                if (ventana.isCitaAtendida()) {
                    Object[] datosCita = new Object[6];
                    for (int i = 0; i < 6; i++) {
                        //Obtención de todos los datos de la cita
                        datosCita[i] = tablaCitasAgendadas.getValueAt(fila, i);
                    }

                    //Consultar en que estado quedó la cita
                    datosCita[5] = ventana.getEstadoCita();

                    //Actualizarlo en el CSV
                    actualizarEstadoCitaEnCSV(idCita, ventana.getEstadoCita());

                    //Casteo de la tabla a un modelo por defecto
                    DefaultTableModel modeloAtendidas = 
                        (DefaultTableModel) tablaCitasAtendidas.getModel();
                    modeloAtendidas.addRow(datosCita);

                    DefaultTableModel modeloAgendadas = 
                        (DefaultTableModel) tablaCitasAgendadas.getModel();
                    modeloAgendadas.removeRow(fila);

                    javax.swing.JOptionPane.showMessageDialog(frmMedico.this, 
                        "Cita actualizada correctamente");
                }
            }
        });
    }
    
    //Impresión de información breve de la cita
    private void verDetalles() {
        int fila = tablaCitasAtendidas.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cita para ver detalles");
            return;
        }
        
        String idCita = (String) tablaCitasAtendidas.getValueAt(fila, 0);
        String paciente = (String) tablaCitasAtendidas.getValueAt(fila, 3);
        String fecha = tablaCitasAtendidas.getValueAt(fila, 1).toString();
        
        String detalles = String.format(
            "DETALLES DE LA CITA\n\n" +
            "ID: %s\nPaciente: %s\nFecha: %s",
            idCita, paciente, fecha
        );
        
        javax.swing.JOptionPane.showMessageDialog(this, detalles, 
            "Detalles", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void cerrarSesion() {
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Está seguro que desea cerrar sesión?", 
        "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        frmlogin login = new frmlogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(frmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new frmMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JLabel lSistemaGestionM;
    private javax.swing.JPanel pCitasAgendadas;
    private javax.swing.JPanel pCitasAtendidas;
    private javax.swing.JPanel pEncabezadoM;
    private javax.swing.JTable tablaCitasAgendadas;
    private javax.swing.JTable tablaCitasAtendidas;
    private javax.swing.JTabbedPane tabpCitasMedicas;
    // End of variables declaration//GEN-END:variables
}
